id: P17D7368F
initial_creation_type: ocr
source_metadata:
  volumes:
    16a972f6adcd459c8a6ca8f12815cada:
      base_file: v115.txt
      image_group_id: I1PD95960
      title: མདོ་སྡེ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་མདོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1829
      volume_number: 115
